config/routes.rb
MyNotes::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users

  resources :notes do
    get "search", :on => :collection
  end

  root :to => "notes#index"

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :content, :title

  validates_presence_of :content, :title
  validates_length_of :content, :maximum => 50

  belongs_to :user

  self.per_page = 3

  def self.search(keywords)
    where('lower(title) like :keywords OR lower(content) like :keywords', :keywords => "%#{keywords.downcase}%")
  end

  def as_json(opts={})
    { :title => self.title, :content => self.content, :user => self.user.name }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name

  validates_presence_of :name

  has_many :notes

  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!

  #methods for ActiveAdmin
  def authenticate_admin_user!
    redirect_to(new_user_session_path) and return if user_signed_in? && !current_user.admin?
    authenticate_user!
  end

  def current_admin_user
    return nil if user_signed_in? && !current_user.admin?
    current_user
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:index, :show, :search]

  # GET /notes
  # GET /notes.json
  def index
    if user_signed_in?
      @notes = current_user.notes.paginate :page => params[:page]
    else
      @notes = Note.paginate :page => params[:page]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  def search
    @keywords = params[:keywords]

    if user_signed_in?
      @notes = current_user.notes.search(@keywords).paginate :page => params[:page]
    else
      @notes = Note.search(@keywords).paginate :page => params[:page]
    end

    render :index
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])
    @note.user = current_user

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyNotes</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to 'MyNotes', root_path, :class => "brand" %>
          <ul class="nav pull-right">
            <% if user_signed_in? %>
              <li><%= link_to current_user.name, edit_user_registration_path %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to 'Register', new_user_registration_path %></li>
              <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <% if flash[:notice].present? %>
        <div class="alert alert-success"><%= flash[:notice]%></div>
      <% end %>

      <% if flash[:alert].present? %>
        <div class="alert alert-error"><%= flash[:alert]%></div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/notes/_form.html.erb
<%= simple_form_for @note, :html => {:class => 'form-vertical' } do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, :input_html => { :class => "span6" } %>
  <%= f.input :content, :input_html => { :class => "span6" } %>
  <%= f.submit :class => "btn" %>
<% end %>

app/views/notes/_note.html.erb
<tr>
  <td><%= link_to note.title, note %></td>
  <td><%= link_to note.content, note %></td>
  <% if user_signed_in? %>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
    <td><%= link_to 'Destroy', note, :confirm => 'Are you sure?', :method => :delete %></td>
  <% end %>
</tr>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<div id="search">
  <%= form_tag(search_notes_path, :method => "get") do %>
   <%= text_field_tag(:keywords, @keywords) %>
   <%= submit_tag "Search", :class => "btn" %>
  <% end %>
</div>

<table class="table table-bordered table-striped">
  <tr>
    <th>Title</th>
    <th>Content</th>
    <% if user_signed_in? %>
      <th></th>
      <th></th>
    <% end %>
  </tr>

  <%= render @notes %>
</table>

<%= will_paginate @notes %>
<br/>

<% if user_signed_in? %>
  <%= link_to 'New Note', new_note_path, :class => "btn" %>
<% end %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @note.title %>
</p>

<p>
  <b>Content:</b>
  <%= @note.content %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>